#pragma once

#include<vector>

typedef std::vector<std::vector<int>> level_list;

#define TILE_SIZE 64 // Very important value used alot!

#define FLOORS_WALLS 4242
#define FLOOR1 FLOORS_WALLS+0
#define WALL_TOP FLOORS_WALLS+1
#define WALL_BOTTOM FLOORS_WALLS+2
#define WALL_LEFT FLOORS_WALLS+3
#define WALL_RIGHT FLOORS_WALLS+4
#define WALL_BOTTOM_LEFT_CORNER FLOORS_WALLS+5
#define WALL_TOP_LEFT_CORNER FLOORS_WALLS+6
#define WALL_BOTTOM_RIGHT_CORNER FLOORS_WALLS+7
#define WALL_TOP_RIGHT_CORNER FLOORS_WALLS+8

static level_list TEST_LEVEL =
{
	{ WALL_TOP_LEFT_CORNER, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP_RIGHT_CORNER },
	{ WALL_LEFT, FLOOR1, FLOOR1, FLOOR1, FLOOR1, WALL_TOP, WALL_TOP, WALL_TOP, WALL_TOP, WALL_RIGHT },
	{ WALL_LEFT, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, WALL_RIGHT },
	{ WALL_LEFT, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, FLOOR1, WALL_RIGHT },
	{ WALL_LEFT, FLOOR1, FLOOR1, FLOOR1, FLOOR1, WALL_RIGHT },
	{ WALL_LEFT, FLOOR1, FLOOR1, FLOOR1, FLOOR1, WALL_RIGHT },
	{ WALL_BOTTOM_LEFT_CORNER, WALL_BOTTOM, WALL_BOTTOM, WALL_BOTTOM, WALL_BOTTOM, WALL_BOTTOM_RIGHT_CORNER },
};